### ISSUE TITLE
Create an index file for my website

### ISSUE THREAD

**Issue by SefisoMonama** [SefisoMonama/cv-sefiso-monama#1]

**Comment by dabarnard** [comment]
Do you see that this issue is still open? It is because you didn't mention it in your PR. If you had added a description saying:

Closes #1 then it would have moved it automatically.

For now, you can just manually comment here "Closed in PR #2 " and then close the issue manually

**Comment by SefisoMonama** [comment]
closed in PR #2

**Comment by dabarnard** [comment]
@SefisoMonama , do you see that the markup wasn't applied to your text for #2 compared to mine - the space is important - please edit the comment so that the markup text is applied
