### ISSUE TITLE
Add minimum required files for website

### ISSUE THREAD

**Issue by dabarnard** [SefisoMonama/cv-sefiso-monama#4]
- Add an empty style.css file to the css folder
- Add an empty scripts.js file to the js folder

Go [here](https://github.com/StartBootstrap/startbootstrap-resume/tree/master/dist) and copy the contents of index.html, style.css and scripts.js to your empty files.

When you open index.html on your local PC, it should look similar to [this](https://startbootstrap.github.io/startbootstrap-resume/):

Once you are happy, create a PR and let me know

**Comment by SefisoMonama** [comment]
in html should i copy everything thats in there then I'll edit it after, or
should i put everything where it is supposed to be?

**Comment by dabarnard** [comment]
The contents of your index.html should be the same as the contents of [this](https://github.com/StartBootstrap/startbootstrap-resume/blob/master/dist/index.html)

The same goes for scripts.js and style.css

**Comment by SefisoMonama** [comment]
I'm done with issue #4

**Comment by SefisoMonama** [comment]
done with issue #4
